# Generated by Django 6.0.7 on 2026-07-13 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('floor_number', models.IntegerField(default=0)),
                ('sharing_type', models.CharField(choices=[('Single', 'Single Sharing'), ('Double', 'Double Sharing'), ('Triple', 'Triple Sharing'), ('Four', 'Four Sharing'), ('Five', 'Five Sharing')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_beds', models.PositiveIntegerField()),
                ('vacant_beds', models.PositiveIntegerField()),
                ('occupied_beds', models.PositiveIntegerField(default=0)),
                ('rent_per_bed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_ac', models.BooleanField(default=False, verbose_name='AC Available')),
                ('has_attached_bathroom', models.BooleanField(default=True)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_wardrobe', models.BooleanField(default=True)),
                ('has_study_table', models.BooleanField(default=False)),
                ('has_fan', models.BooleanField(default=True)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Fully Occupied', 'Fully Occupied')], default='Available', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='pgs.pg')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='rooms.room')),
            ],
        ),
    ]
