# Generated by Django 6.0.7 on 2026-07-13 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='Specific locality name', max_length=100)),
                ('google_maps_link', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Co-Living', 'Co-Living')], max_length=20)),
                ('cover_image', models.ImageField(upload_to='pgs/covers/')),
                ('has_parking', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_ro_water', models.BooleanField(default=False)),
                ('has_food', models.BooleanField(default=False)),
                ('has_laundry', models.BooleanField(default=False)),
                ('has_cleaning', models.BooleanField(default=False)),
                ('has_power_backup', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('has_security_guard', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_pgs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PGImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pgs/gallery/')),
                ('pg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pgs.pg')),
            ],
        ),
    ]
